language: node_js
node_js:
- '10'
install:
- make install
script:
- make test
env:
  secure: Szxx3ECnEacvj27cmmKdGMW7g1fRVc7K2qDdCvDm4pr6WVlLn+OBQYV6cns43JwVbJj4aPct3Tjo/3pMO3J25GFbzwTapm6e3zjEf47k5RhYuPH5qZbvIU+pTujc156Ouzog8axUp/P5z2B+o/EpdxR4wojaxwg2hKb7fTZE+RoWDXzTfDAhJPYvSdKY70O0hUVXq4I947mo/1/ZUFzL1ZGdh5ih1daU8GQOkVPsA5cLDQVLx3Ou53/Uh7dyBKyhH4gxCO5LU+umgGQViEDpG3ms5bw1VGdqAzVjcnSfqrXqNn8GjpZkf3vlXq4sCwnhwAkGwJcphje5piPPD9kDiU/RGcWHwJEmZiOl0MYpXKNRV7dZBqEr8i8bqAQdlh+F7/yX2mEkmu1R9FodTgn0VnStji4pGKOBzP2ADIerC/ZRGHrrZ0LT/9L7ZA6dlI3f+IOpAkBMaDxxzGu74UcGNS5gsu6Gp7mK7+EVU3D5hVfzOVJSkTHjiMrn2/lzvcc99KtMmWNu5tng4GptRBQvGeiAGTUlVIL1V8hYAXoSahLW7v18Uy9y8yBgoI5rxwaX0wKG7XiWnCr9VOAidnd36g6cKCSL2a1AhZ80Hv1qAXVm3XPAl5tbMBpRrwRD6xddR8phKZuTcorqRwCfZgkjL3jpeeFbZferHlB8tE5MdFE=
