language: node_js
node_js:
- '10'
install:
- make install
script:
- make test
env:
  secure: cJJe95TAyoWN7Z8w/XBno/UemR+bWDsD2D8GCjBZnsTYnnkG1o2c/VXoK7FJB+3d2LaSI9c6FwIUPFd3ZBi3tSZlCISXgTRcdzIUi/GMmE7SA/V7CPD80/qeJZC1LB0etR+zMiX3iEDSAhURYqTnUpCVIMi2UIgPb3B3ZvqbS0yesemJvyShJYACGpuAxYnbzjCEexNuFOLF+4zoK5SGslf5Y7CjwYOIBmtNYEDBac4fAJrcYlqlUUY+Y4j+KftRHXndQygPMKwHRZk2wbRWcFl1buOYEx73HYF77serBT1HklQQJFaaNiFYfGMYzvJ67dZxvJFTCpqdgYbh13bWmmXYTKdOA09Ic7fn30fVCHgn4X3LHJy5w3TFzE2G9fYoy3i1DY4+DFnrlAFed7kTGZQQlo+gs/RwISuCkyEhPOwsejNSib/datE4vfOpbFhBCPs5SmxQ2eJdX/DwGXJgUOBJa0OtcZR5qE3A3JmbCrj11F4sBW13gzxkYyGHcUHvJ2cSoivffjTf/pMz5UsrSYxEL1iBay3Tno0tjn215FGTIur3HKI4P/hX4uatItgydIBTiP7tYE9LVExDF4BUMZJN1dJ1G1BScarOWPgiaHtge7lLPbtQ3AzSrDjdvG4fvV8wiRvvK+WpryI4rTgxSDold+dILg3uMpQqQQFzWrc=
