language: node_js
node_js:
- '10'
install:
- make install
script:
- make test
env:
  secure: H5aw9zVsxr88PuEfYUAISdBX0PMt1iD+OuiLS/ldG3IYLmApTFS4op1nXE4CeEGg2TBuTzYaO/EySSZcL1IxBXubMSnGdx6SBTnMFKm9p5Ks4g8k3lwlwJvBsmXhSN7kSPZ290xz3IsT6dTz135dQ6S2QiZVYnXIL47MU7KQFw59RKWAO3Psuyqgg1IxwsFA2dp5hI7fnR1XzCSiN8Sb1Nwez6ngjpxUnM+fOUsIbN6MY8hVXZ2efmuWgLCQGrwwOY4nrRsw2Eud7Pbr5vwcqQijDPpaYgpYzIntBbqu2GCsDFDr8ix1khJNnHVlOd+UuHeqq1XJ+ocgw5hAi2KJ1kXuftnuDdHWkWQEwxWCZ4D2DfbEMnEaYCkOML7msdu7ylo1m0K2oUW8CrTKRF+FBHj7fyqRjadQ+2l2axar7ch34SpPkClfeU3WLw8gnCyieW7+ui0NbmKtBjqe9//AJnsK5Igyp/AAjePMTMkaAmtyf7HMNc8QYs/ut6tA/wcNboxqsd27ZH8h4Sj84sEYAG7J6LjNncanMgw0KMeaF5VvDFh9KoFt9i7YSctLVPW+SJ+bf2GsTVN7llWKr3LA7BiFoKU4DiC+hgGF6BXBF8bdVqE2+RwCAd5YyROl3OvpScYRvL56ovOF7zVFGOGQ1J7vJ9eDIj7LLL+k3mri2Cc=
