language: node_js
node_js:
- '10'
install:
- make install
script:
- make test
env:
  secure: N9VCtqD+NG20ju+BQRPlf2HzRptcBfbet+XN+xH/aIO+j/svIEDU78QJJpnBmC0HzmPQpzyzYurAoBk0pd6dFAgoBr47tIlQmsRuRZ+q03wWPM/q+5qRHoHIY4z+TCplEcchuqiSK+kAQiQ5WAmfd8XwImsYSXmZ2JWM2NdDWfD/XIv3f69ZEyN2JR68InylUDAl4jt4MA3rsp18EeSc6Kehov63/JvpTadNtlZbQMQl02KA074rQJ5oBdz1vyuXtDEr9gAzPTpV6chU34oDz6by85ngOzTNDdXsjLKVzLLfF+7xOE8+q4xiEVkQ0lpt//tUfNEcynD8nYYFkJNQuoA+SOSZJVjndKfJPF5EXqAqnx4kFKqCY5cc02XH0qG+8LKM5QWd9VSkoHqV2NBqTJFJOpJEuThChuYKJi10W4xUj26T6lpmZ1EaNgPdbueV5fN8yS1Wqc5H8kb2cocpVIsQk+DSzbjgayXJnkGbTKjeuRXEz58P6y9I+FmYCyXWPdKj4Z83HIEwDONjH76XLDYjygJz99ZbTKKAsUM8rfWZ0Q2Vgdj4fb290TlhWj3CH+ABZzhodsaIf+/gr68NGgyHRbhprk69lT9qNDpNHq0yu3Onk5NsvojAxWB/NGns/GosIXhsj/nqCx0ZrnGOaUp753tkQSP7aOB67vMQ2ZE=
