language: node_js
node_js:
- '10'
install:
- make install
script:
- make test
env:
  secure: UCaVgiO/ByzIgwgbjI3gbEdLqzVfkn1xRLl8WcwnMmcwsyHS2hBmy3tetKfNquPpvxPrAefpzZBjHuYE3younhgnsHzZ5XGzpmSeKOMYysca89jZ8bbSk3dGAEw3gVIHl38e10on9kTksw5p9135Fkuv9PI96i939lwSxzDxly4u937kx9E10yotsJKoZnpnoXfbiXv93XiWWTIdop7trw+IiZLGeY/1hYWbMoXMXbPWWs1N/ewiskb7rRFspyMSYnGVKqtjtda/jra/BRVucOVBLUcz2iSzmTceo/XwgbdH1WMKsiqMOF14xLidwR27NBUvDuXwyk0lcuCqIDlBOSC4Asile6kfMvLpUx797106FrUGUWHDTyMcNMU3QGLOWy8kpHqObIs7rX5ZQQUTYibQNWJPk+SU7N51pFYltBvkQGWN88IQtQ+h6pqXQqVnGQs88Ih9lJ8D5juiRO38vxzNXco++oJJ2zLMtZCjpMXyTQemoUf8fnp1JY+vJaIU6ro+D2JEhX0+yP0fBhES142AVFsSPb7NFJ5oMrQ9gie2XefUqYtEfKrAbIlOi56G6uHbgoP8mhHN/uAshhWPzYePtObEtgSHVRUU/woQRm0mctZeP/7qoXCWx9tmXFifszVWg3Kaqomw2yzzW2X1ZmFqH5LdG7y31ftPC4Yl89U=
