language: node_js
node_js:
- '10'
install:
- make install
script:
- make test
env:
  secure: d99Yftg0euHEej2d8wW4n7doyUpY3YRAVANwWS/uAUS6E4DdwKeCjRUGMTxKunomyLfynZi4lAM6I3GGHs2yJFb5qnqly5krwox0y7ORJTgILJxFEkUT/tKVrJyWQNLklB0cNXYPcq0WvXdhwdHod12wjAkvzOyxY1A3DclYioWYzZGmChIjsHnDFhoBPJggG+4lY2ZMiR+7ndDjZyiOARNjPHJBwY2l830G9viXqQtRRAg+hWl70B1354ytHfgwOBq/j8qfQ10ukoItXABac/qkjVngZPfxri1XyzXUEFxSSItennMj2MISFZlzb8d2u4dl1eefWAa5HME/B/40U5jDNp5QfxkghP60CAWeto3keiOUUNNH8DVncdpEmNlh7KUaJotn4mz58sP8T05crrgc1chSb1f2CFmdxYD0CiY+XB8UQ4lYtDttQYxrA2WHV7BVHBiii0GMxC0Ys8d04EoWlbT51pLTMAQRxoHdRNvpb7mMMy4pE6AABFL7o8c4DSJ//tx4+keRMskhnosT70CQE3D1Ope/eJOwx1wJ7gHvvVgzKeyGfCRHwE3qPQNawDcbGKTm6k4Whv7QjRPh/dPnjMJpHQ6moOt1QJHIV1D7yhrlkI2F93iL2aSbfe0okGWe/FQmYQMDMIP0kq+A8YdSTL5e76WFk+6ktrsb4jk=
