language: node_js
node_js:
- '10'
install:
- make install
script:
- make test
env:
  secure: GNRZ96hEh17IQa8kGZaZTdKSYFuBDGpMAntUroAhRXjB3cceDz7CDQ1WVQgcuEBFD433mnAliIQzKZQv5VDzaK/uqnpWTV//9i9nTkSHGWzdb/KtaR73LKhItwvJvXn9sIaqAksb/qrMJpBia8icEsgCJgerN++eNVVupwA4vvRniIaE5veVrmNtVqdYdT2cyTZo0sW5cS8Aq0vGVdVhPKZBdl2bhpW7wiUwbzgPd9R12b6zAuIoeCXQw4tVgwKL1VzEKX3LtmEjN8cQ7zcl1bvow06zV4ozgAEzXBKa+OcMj4MikFAf2H6r1d5mUlFBBdQxnOLglUULdZEPN7PeDPpXJYiOJFrUrzSbnSTs0q1soxbUC1vA9AqHoLyiEyvMQtHpDrW3DSGcn4XXGckQIzTfZe4XiM3zpFyiDNpOW+U5XSuw1EMvYlO74q56sjfs336N3bq47sOWW5U3NAUjDz3T4CiG5jaWqANV30+koK5LWm+48IBTAkJY9BG2a1C1TSAn8mMqNIVMi+De26QmJa4kCyH+odPrCiP5POpHYdEun1diEAj5JCd3AkBsjIU5MB0OZc1RYJ08/CyxAI1QqT7br78AWsXalPK4LUKGRRlukgV9eNFaLkAAmaw0iuamDdpchVpGtQnPxi1Q4v4Kzevi1gzv+3YBIR5AM+R2pds=
