language: node_js
node_js:
- '10'
install:
- make install
script:
- make test
env:
  secure: IFG6yYwTNkl70WNvkPlyXNb/L08lk9d+3nKir/duZ3povQNiIzlG2Odojqt1Og3+C7oMOHjBng2xGA6nJ1zPjNBltY/yyaDUp+iyg4zmy4CcJGDFOVh+yL3WHxvKmfVgv7wsuxsTzzcLPxpUbFyaG/Btpyg9Vhh1AVqjVt9VyQA2YU2w/yeOilGxSYpx5MQSeXfEkat1jDrvEGiIGQfukt/M5YaeubQm8Yjyxr2kqwpR7VfMkOFPigrFtw4PTppuHZEcQxK16wPSdfwTLma1Ci5PzJIGOLcceSdTxiW/AP4lGwBrEkvkuAm3s9S3TNb/LIHEofsV/2n71UUgVsHYEn1s2GInr82nY+2nADJYwmxH81a8wiboWngE8xq2thMjm2Zw9gjA+tp3eqVCdYHE+Q+seeJWGrY4cmD4pK/3Y4h0EsHMbm135nLg727iC7VhanMIU19/PaxRfV1PbUbZ87kW0MA45MCrnuTW30ZH4cXsomOhuBaN1LMbpsh8c3I+Vu1wzgJsSDnV996XbFnyqjY8G7z6dGziW5NzrExgBT59ziK/bArr4S6ck4t3iPxtFy1iK60xLwSiDZqzWRQEQd1/Niq99XPYFveSimeDg1o94SLI4xbLWjuZKJQOku0M6skGLLKXQN3SR1nO8O71kBm2XkzIBpDsEDSjVEQ0S/Y=
