module.exports = {
  githubId: 'YOUR_GITHUB_ID',
  githubPw: 'YOUR_GITHUB_PW',
  githubProjectUrl: 'YOUR_GITHUB_PROJECT_URL',
  githubToken: 'YOUR_GITHUB_TOKEN',
  screenshotPath: '/tmp/progress.png',
  viewportWidth: 2560,
  viewportHeight: 1024,
  clipX: 678,
  clipY: 245,
  clipWidth: 1000,
  viewportWidth: 2560,
  viewportHeight: 1024,
  clipX: 678,
  clipY: 245,
  clipWidth: 1000,
  clipHeight: 450,
  gcpProjectId: 'YOUR_GCP_PROJECT_ID',
  gcsBucket: 'YOUR_GCS_BUCKET',
  esaTeamId: 'YOUR_ESA_TEAM_ID',
  esaAccessToken: 'YOUR_ESA_TOKEN',
  esaCategory: 'YOUR_ESA_CATEGORY',
};
